// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0OCqJ8wdExn0kMJ2_mABOCNIIITW18U',
    appId: '1:746777493439:web:73997796fbbac1f9dbab0a',
    messagingSenderId: '746777493439',
    projectId: 'chats-app-with-flutter',
    authDomain: 'chats-app-with-flutter.firebaseapp.com',
    storageBucket: 'chats-app-with-flutter.firebasestorage.app',
    measurementId: 'G-XR08E18K19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFQl9vHkxezHJJDOqgcsW8_vLBawOjPg',
    appId: '1:746777493439:android:49a44bdee51d0789dbab0a',
    messagingSenderId: '746777493439',
    projectId: 'chats-app-with-flutter',
    storageBucket: 'chats-app-with-flutter.firebasestorage.app',
  );
}
